### ISSUE TITLE
Error: Failed to download module

### ISSUE THREAD

**Issue by ehalsey** [aashari/boilerplate-lambda-typescript#1]
While running terraform init

Error: Failed to download module
│
│ Could not download module "naming-layer" (main.tf:86) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0":     
│ error downloading 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning     
│ into '.terraform\modules\naming-layer'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.

**Comment by aashari** [comment]
ahhh I see, my bad @ehalsey, I'm working on fixing this issue

**Comment by aashari** [comment]
Hi @ehalsey, can you try again using the latest update from master branch? thanks
