### ISSUE TITLE
Similar issue found terraform init

### ISSUE THREAD

**Issue by ehalsey** [aashari/boilerplate-lambda-typescript#2]
@aashari no luck.  Looks similar to the previous issue.

PS D:\boilerplate-lambda-typescript> terraform init
Initializing modules...
Downloading git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0 for dynamodb-table-name...
Downloading git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0 for lambda-function-name...
Downloading git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0 for lambda-layer-name...
╷
│ Error: Failed to download module
│ 
│ Could not download module "dynamodb-table-name" (main.tf:44) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\dynamodb-table-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│ 
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lambda-function-name" (main.tf:36) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\lambda-function-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lambda-layer-name" (main.tf:29) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\lambda-layer-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "dynamodb-table-name" (main.tf:44) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\dynamodb-table-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "dynamodb-table-name" (main.tf:44) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\dynamodb-table-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lambda-function-name" (main.tf:36) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\lambda-function-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "dynamodb-table-name" (main.tf:44) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\dynamodb-table-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lambda-function-name" (main.tf:36) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\lambda-function-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lambda-layer-name" (main.tf:29) source code from "git::ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0": error downloading
│ 'ssh://git@github.com/traveloka/terraform-aws-resource-naming.git?ref=v0.22.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\lambda-layer-name'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
│
╵

**Comment by aashari** [comment]
Hi @ehalsey, can you try resolving the issue by using this solution?
https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository

```
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
```
